version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
    open-pull-requests-limit: 10
    target-branch: master
    groups:
      dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'maint'
  - package-ecosystem: npm
    directory: '/examples/aws-secrets-example'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'maint'
    labels:
      - 'dependabot'
      - 'examples'
  - package-ecosystem: npm
    directory: '/examples/azure-secrets-example'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'maint'
    labels:
      - 'dependabot'
      - 'examples'
  - package-ecosystem: npm
    directory: '/examples/bitwarden-secrets-example'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'maint'
    labels:
      - 'dependabot'
      - 'examples'
  - package-ecosystem: npm
    directory: '/examples/custom-secrets-example'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'maint'
    labels:
      - 'dependabot'
      - 'examples'
  - package-ecosystem: npm
    directory: '/examples/gcp-secrets-example'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'maint'
    labels:
      - 'dependabot'
      - 'examples'
